list: $/octobro/promo/models/promo/columns.yaml
modelClass: Octobro\Promo\Models\Promo
title: Promos
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'octobro/promo/promos/update/:id'
